### ISSUE TITLE
IA stopée quand rejoint au cbt

### ISSUE THREAD

**Issue by arkwak** [friendlydofus/FriendlyBot.SimpleAPI#13]
lorsque quelqu un rejoint un combat lancé par le bot, L'IA (cra) ne fonctionne plus et donc laisse le temps s'écouler

**Comment by Shyrogan** [comment]
Euh, je n'ai pas ce cas. T'es sûr?

**Comment by arkwak** [comment]
oui j ai eu le cas quand un iop est rentré dans mon combat
